### ISSUE TITLE
Proper Way To Make TODO List

### ISSUE THREAD

**Issue by Uniminin** [MajorGamerJay/junamer#1]
- **Todo**:
	- [x] Prepare Todo List
	- [ ] Provide Abstract & Proof-of-concept (**WIP**)
	- [ ] Implement (**WIP**)
	- [ ] Peer-Review
	- [ ] Documentation
	- [ ] Implement Tests
	- [ ] CI/CD/CA Optimization
	- [ ] Prepare README.txt
	- [ ] Provide LICENSE

**Comment by MajorGamerJay** [comment]
ty
